# Generated by Django 4.1.5 on 2023-01-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='ModeloDoArquivo',
        ),
    ]
