# Generated by Django 4.1.5 on 2023-01-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_rename_filemodel_modelodoarquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeloDoArquivo',
            new_name='FileModel',
        ),
    ]
