# Generated by Django 4.1.5 on 2023-01-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_rename_modelodoarquivo_filemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='ModelDoArquivo',
        ),
    ]
